import { Garland, Category, Occasion, PickupSlot } from '@/types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Wedding', slug: 'wedding', image_url: null, display_order: 1, is_active: true },
  { id: '2', name: 'Pooja', slug: 'pooja', image_url: null, display_order: 2, is_active: true },
  { id: '3', name: 'Temple', slug: 'temple', image_url: null, display_order: 3, is_active: true },
  { id: '4', name: 'Birthday', slug: 'birthday', image_url: null, display_order: 4, is_active: true },
  { id: '5', name: 'Festival', slug: 'festival', image_url: null, display_order: 5, is_active: true },
  { id: '6', name: 'Function', slug: 'function', image_url: null, display_order: 6, is_active: true },
];

export const MOCK_OCCASIONS: Occasion[] = [
  { id: '1', name: 'Wedding', slug: 'wedding', icon: '💒', display_order: 1, is_active: true },
  { id: '2', name: 'Pooja', slug: 'pooja', icon: '🪔', display_order: 2, is_active: true },
  { id: '3', name: 'Function', slug: 'function', icon: '🎉', display_order: 3, is_active: true },
  { id: '4', name: 'Birthday', slug: 'birthday', icon: '🎂', display_order: 4, is_active: true },
  { id: '5', name: 'Temple', slug: 'temple', icon: '🛕', display_order: 5, is_active: true },
  { id: '6', name: 'Festival', slug: 'festival', icon: '🌟', display_order: 6, is_active: true },
  { id: '7', name: 'Special', slug: 'special', icon: '🌸', display_order: 7, is_active: true },
];

export const MOCK_GARLANDS: Garland[] = [
  {
    id: '1',
    name: 'Rose Wedding Garland',
    slug: 'rose-wedding-garland',
    description: 'A stunning garland made with fresh red roses, perfect for weddings and special occasions. Each bloom is handpicked for maximum freshness and beauty.\n\n✨ Packaging Details: Handcrafted as 1 Pair (2 Garlands — matching Bride & Groom set). Others come as single garlands. As required, you can increase the count above for additional sets.',
    price: 650,
    category_id: '1',
    occasion_id: '1',
    flower_type: 'Rose',
    images: ['/images/garland-rose.jpg'],
    video_url: null,
    is_available: true,
    is_featured: true,
    is_popular: true,
    stock_qty: 20,
    collection_tag: 'Wedding Season',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '1', name: 'Wedding', slug: 'wedding', image_url: null, display_order: 1, is_active: true },
    occasion: { id: '1', name: 'Wedding', slug: 'wedding', icon: '💒', display_order: 1, is_active: true },
  },
  {
    id: '2',
    name: 'Jasmine Pooja Garland',
    slug: 'jasmine-pooja-garland',
    description: 'Fresh jasmine garland with divine fragrance, ideal for daily pooja and temple offerings. The pure white blossoms bring serenity and peace.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 450,
    category_id: '2',
    occasion_id: '2',
    flower_type: 'Jasmine',
    images: ['/images/garland-jasmine.jpg'],
    video_url: null,
    is_available: true,
    is_featured: true,
    is_popular: true,
    stock_qty: 30,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '2', name: 'Pooja', slug: 'pooja', image_url: null, display_order: 2, is_active: true },
    occasion: { id: '2', name: 'Pooja', slug: 'pooja', icon: '🪔', display_order: 2, is_active: true },
  },
  {
    id: '3',
    name: 'Grand Wedding Garland',
    slug: 'grand-wedding-garland',
    description: 'A majestic double-strand garland combining roses, marigolds, and jasmine. Perfect for the main couple at weddings — truly unforgettable.\n\n✨ Packaging Details: Handcrafted as 1 Pair (2 Garlands — matching Bride & Groom set). Others come as single garlands. As required, you can increase the count above for additional sets.',
    price: 1200,
    category_id: '1',
    occasion_id: '1',
    flower_type: 'Mixed',
    images: ['/images/garland-grand.jpg'],
    video_url: null,
    is_available: true,
    is_featured: true,
    is_popular: false,
    stock_qty: 15,
    collection_tag: 'Wedding Season',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '1', name: 'Wedding', slug: 'wedding', image_url: null, display_order: 1, is_active: true },
    occasion: { id: '1', name: 'Wedding', slug: 'wedding', icon: '💒', display_order: 1, is_active: true },
  },
  {
    id: '4',
    name: 'Marigold Temple Garland',
    slug: 'marigold-temple-garland',
    description: 'Vibrant golden marigold garland for temple worship. Freshly strung daily to ensure maximum fragrance and color.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 280,
    category_id: '3',
    occasion_id: '5',
    flower_type: 'Marigold',
    images: ['/images/garland-marigold.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: true,
    stock_qty: 50,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '3', name: 'Temple', slug: 'temple', image_url: null, display_order: 3, is_active: true },
    occasion: { id: '5', name: 'Temple', slug: 'temple', icon: '🛕', display_order: 5, is_active: true },
  },
  {
    id: '5',
    name: 'Lotus Birthday Garland',
    slug: 'lotus-birthday-garland',
    description: 'Delicate lotus and lily garland, elegantly arranged for birthday celebrations. Add a touch of grace to your special day.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 550,
    category_id: '4',
    occasion_id: '4',
    flower_type: 'Lotus',
    images: ['/images/garland-lotus.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: false,
    stock_qty: 10,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '4', name: 'Birthday', slug: 'birthday', image_url: null, display_order: 4, is_active: true },
    occasion: { id: '4', name: 'Birthday', slug: 'birthday', icon: '🎂', display_order: 4, is_active: true },
  },
  {
    id: '6',
    name: 'Navaratri Festival Garland',
    slug: 'navaratri-festival-garland',
    description: 'Vibrant multi-colored garland with chrysanthemums, roses, and marigolds celebrating the spirit of Navaratri.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 750,
    category_id: '5',
    occasion_id: '6',
    flower_type: 'Mixed',
    images: ['/images/garland-festival.jpg'],
    video_url: null,
    is_available: true,
    is_featured: true,
    is_popular: true,
    stock_qty: 25,
    collection_tag: 'Navaratri',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '5', name: 'Festival', slug: 'festival', image_url: null, display_order: 5, is_active: true },
    occasion: { id: '6', name: 'Festival', slug: 'festival', icon: '🌟', display_order: 6, is_active: true },
  },
  {
    id: '7',
    name: 'Chrysanthemum Function Garland',
    slug: 'chrysanthemum-function-garland',
    description: 'Beautiful white chrysanthemum garland perfect for felicitation ceremonies, cultural programs, and formal functions.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 380,
    category_id: '6',
    occasion_id: '3',
    flower_type: 'Chrysanthemum',
    images: ['/images/garland-chrysanthemum.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: true,
    stock_qty: 40,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '6', name: 'Function', slug: 'function', image_url: null, display_order: 6, is_active: true },
    occasion: { id: '3', name: 'Function', slug: 'function', icon: '🎉', display_order: 3, is_active: true },
  },
  {
    id: '8',
    name: 'Kanakambaram Pooja Garland',
    slug: 'kanakambaram-pooja-garland',
    description: 'Traditional orange kanakambaram flower garland — a classic offering with deep cultural significance in South Indian households.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 320,
    category_id: '2',
    occasion_id: '2',
    flower_type: 'Kanakambaram',
    images: ['/images/garland-kanakambaram.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: false,
    stock_qty: 35,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '2', name: 'Pooja', slug: 'pooja', image_url: null, display_order: 2, is_active: true },
    occasion: { id: '2', name: 'Pooja', slug: 'pooja', icon: '🪔', display_order: 2, is_active: true },
  },
  {
    id: '9',
    name: 'Royal Bridal Garland Set',
    slug: 'royal-bridal-garland-set',
    description: 'An exquisite bridal garland set with fragrant roses, jasmine, and tuberose. Two matching garlands for bride and groom, beautifully crafted.\n\n✨ Packaging Details: Handcrafted as 1 Pair (2 Garlands — matching Bride & Groom set). Others come as single garlands. As required, you can increase the count above for additional sets.',
    price: 2200,
    category_id: '1',
    occasion_id: '1',
    flower_type: 'Mixed',
    images: ['/images/garland-bridal.jpg'],
    video_url: null,
    is_available: true,
    is_featured: true,
    is_popular: false,
    stock_qty: 5,
    collection_tag: 'Wedding Season',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '1', name: 'Wedding', slug: 'wedding', image_url: null, display_order: 1, is_active: true },
    occasion: { id: '1', name: 'Wedding', slug: 'wedding', icon: '💒', display_order: 1, is_active: true },
  },
  {
    id: '10',
    name: 'Tuberose Special Garland',
    slug: 'tuberose-special-garland',
    description: 'Luxurious tuberose garland with an intoxicating fragrance. Perfect for special occasions when you want to create an unforgettable impression.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 890,
    category_id: '6',
    occasion_id: '7',
    flower_type: 'Tuberose',
    images: ['/images/garland-tuberose.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: true,
    stock_qty: 12,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '6', name: 'Function', slug: 'function', image_url: null, display_order: 6, is_active: true },
    occasion: { id: '7', name: 'Special', slug: 'special', icon: '🌸', display_order: 7, is_active: true },
  },
  {
    id: '11',
    name: 'Pongal Harvest Garland',
    slug: 'pongal-harvest-garland',
    description: 'Celebrate Pongal with a traditional garland of marigolds and banana flowers. Brings the essence of harvest prosperity into your home.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 420,
    category_id: '5',
    occasion_id: '6',
    flower_type: 'Marigold',
    images: ['/images/garland-pongal.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: false,
    stock_qty: 30,
    collection_tag: 'Pongal',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '5', name: 'Festival', slug: 'festival', image_url: null, display_order: 5, is_active: true },
    occasion: { id: '6', name: 'Festival', slug: 'festival', icon: '🌟', display_order: 6, is_active: true },
  },
  {
    id: '12',
    name: 'Mixed Flower Daily Garland',
    slug: 'mixed-flower-daily-garland',
    description: 'Fresh mixed flower garland with seasonal blooms — affordable, fragrant, and perfect for daily devotion or gifting.\n\n✨ Packaging Details: Handcrafted as Single Garland (1 Piece). (Note: All wedding garlands come as a 2-garland pair). As required, you can increase the count above for your celebration.',
    price: 180,
    category_id: '2',
    occasion_id: '2',
    flower_type: 'Mixed',
    images: ['/images/garland-mixed.jpg'],
    video_url: null,
    is_available: true,
    is_featured: false,
    is_popular: true,
    stock_qty: 60,
    collection_tag: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
    category: { id: '2', name: 'Pooja', slug: 'pooja', image_url: null, display_order: 2, is_active: true },
    occasion: { id: '2', name: 'Pooja', slug: 'pooja', icon: '🪔', display_order: 2, is_active: true },
  },
];

// Generate flexible pickup time intervals between 8:00 AM and 8:00 PM — 100% available without order limits
export function generateMockSlots(dateStr: string): PickupSlot[] {
  const intervals = [
    { start: '08:00', end: '10:00' },
    { start: '10:00', end: '12:00' },
    { start: '12:00', end: '14:00' },
    { start: '14:00', end: '16:00' },
    { start: '16:00', end: '18:00' },
    { start: '18:00', end: '20:00' },
  ];
  return intervals.map((s, i) => ({
    id: `slot-${dateStr}-${i}`,
    date: dateStr,
    start_time: s.start,
    end_time: s.end,
    max_orders: 99999,
    booked_count: 0,
    is_available: true,
  }));
}

export const MOCK_REVIEWS = [
  {
    id: '1',
    name: 'Priya Subramaniam',
    rating: 5,
    text: "The Rose Wedding Garland was absolutely breathtaking! Fresh, fragrant, and beautifully arranged. Everyone at the wedding was amazed. Will definitely order again!",
    garland: 'Rose Wedding Garland',
    date: '2 days ago',
    avatar: 'PS',
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    rating: 5,
    text: "Ordered the Jasmine Pooja Garland and it arrived fresh and fragrant. The pre-order system is so convenient — I could pick it up exactly when I needed it.",
    garland: 'Jasmine Pooja Garland',
    date: '1 week ago',
    avatar: 'RK',
  },
  {
    id: '3',
    name: 'Meena Krishnan',
    rating: 5,
    text: "Malligai Garlands has the best flowers in the city! The Grand Wedding Garland was even more beautiful in person. The pickup was smooth and the flowers stayed fresh all day.",
    garland: 'Grand Wedding Garland',
    date: '2 weeks ago',
    avatar: 'MK',
  },
  {
    id: '4',
    name: 'Anand Venkat',
    rating: 4,
    text: "Great quality garlands at reasonable prices. The online ordering process is simple and the time slot system is brilliant — no waiting at the shop!",
    garland: 'Marigold Temple Garland',
    date: '3 weeks ago',
    avatar: 'AV',
  },
];
